on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: maven
    - uses: whelk-io/maven-settings-xml-action@v22
      with:
        githubServer: false
        servers: |
          [{
              "id": "repo-frufq",
              "username": "${{ secrets.MAVEN_USERNAME }}",
              "password": "${{ secrets.MAVEN_PASSWORD }}"
          }]
        mirrors: |
          [{
              "id": "mirror",
              "name": "mirror",
              "mirrorOf": "central,jcenter,!repo-frufq",
              "url": "https://maven.aliyun.com/nexus/content/groups/public"
          }]
        repositories: |
          [
              {
                  "id": "central",
                  "url": "https://maven.aliyun.com/nexus/content/groups/public",
                  "releases": {
                      "enabled": true
                  },
                  "snapshots": {
                      "enabled": false
                  }
              },
              {
                  "id": "snapshots",
                  "url": "https://maven.aliyun.com/nexus/content/groups/public",
                  "releases": {
                      "enabled": false
                  },
                  "snapshots": {
                      "enabled": true
                  }
              },
              {
                  "id": "repo-frufq",
                  "name": "https://packages.aliyun.com/6810844781f0d609ac6a2c51/maven/repo-frufq",
                  "url": "url",
                  "releases": {
                      "enabled": true
                  },
                  "snapshots": {
                      "enabled": true
                  }
              }
          ]
        pluginRepositories: |
          [
              {
                  "id": "central",
                  "url": "https://maven.aliyun.com/nexus/content/groups/public",
                  "releases": {
                      "enabled": true
                  },
                  "snapshots": {
                      "enabled": false
                  }
              },
              {
                  "id": "snapshots",
                  "url": "https://maven.aliyun.com/nexus/content/groups/public",
                  "releases": {
                      "enabled": false
                  },
                  "snapshots": {
                      "enabled": true
                  }
              },
              {
                  "id": "repo-frufq",
                  "url": "https://packages.aliyun.com/6810844781f0d609ac6a2c51/maven/repo-frufq",
                  "releases": {
                      "enabled": true
                  },
                  "snapshots": {
                      "enabled": true
                  }
              }
          ]
        active_profiles: |
          [
            "rdc"
          ]
        profiles: |
          [
              {
                  "id": "rdc",
                  "properties": {
                      "altReleaseDeploymentRepository": "repo-frufq::default::https://packages.aliyun.com/6810844781f0d609ac6a2c51/maven/repo-frufq",
                      "altSnapshotDeploymentRepository": "repo-frufq::default::https://packages.aliyun.com/6810844781f0d609ac6a2c51/maven/repo-frufq"
                  }
              }
          ]
        output_file: .m2/settings.xml

    - name: test
      run: |
        cat .m2/settings.xml
        
    
    # - name: Build with Maven
    #   run:
    #     mvn deploy
